apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nailox1zb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nailox1zb-go 
  name: nailox1zb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nailox1zb-go 
